version: '3.8'

services:
  app:
    build: .
    container_name: production_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    restart: always

  mongo:
    image: mongo:latest
    container_name: production_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: